---

- name: Instalando zsh via apt
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt:
    name: zsh
    state: present
    update_cache: yes

- name: Instalando zsh via pacman
  when: ansible_distribution == 'Archlinux'
  pacman:
    name: zsh
    state: present
    update_cache: yes

- name: Instalando git via apt
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt:
    name: git
    state: present
    update_cache: yes

- name: Instalando git via pacman
  when: ansible_distribution == 'Archlinux'
  pacman:
    name: git
    state: present
    update_cache: yes

- name: Copiando /tmp/ohmyzsh.sh
  template:
    src: ohmyzsh.sh
    dest: /tmp/ohmyzsh.sh
    owner: root
    group: root
    mode: a+rx
    force: yes

- name: Instalando oh-my-zsh
  command:
    cmd: /tmp/ohmyzsh.sh

- name: Copiando ~/.zshrc
  copy:
    src: zshrc
    dest: "/home/{{ ansible_distribution | lower }}/.zshrc"
    owner: "{{ ansible_distribution | lower }}"
    group: "{{ ansible_distribution | lower }}"
    force: yes

- name: Deletando /tmp/ohmyzsh.sh
  file:
    path: /tmp/ohmyzsh.sh
    state: absent
...