---

- name: Atualizando pacotes via apt
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - group_names | select('search','EMC') | list | count > 0
  apt:
    upgrade: dist
    update_cache: yes
  notify: Reiniciando o sistema

- name: Atualizando pacotes via apt
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - group_names | select('search','KVM') | list | count > 0
  apt:
    upgrade: dist
    update_cache: yes
  notify: Desligando o sistema

- name: Atualizando pacotes via pacman
  when:
    - ansible_distribution == 'Archlinux'
    - group_names | select('search','EMC') | list | count > 0
  pacman:
    upgrade: yes
    update_cache: yes
  notify: Reiniciando o sistema

- name: Atualizando pacotes via pacman
  when:
    - ansible_distribution == 'Archlinux'
    - group_names | select('search','KVM') | list | count > 0
  pacman:
    upgrade: yes
    update_cache: yes
  notify: Desligando o sistema

- name: Atualizando pacotes via apt
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - group_names | select('search','Main') | list | count > 0
  apt:
    upgrade: dist
    update_cache: yes
  notify: Reiniciando o sistema
...