---

- name: Instalando qemu-guest-agent via apt
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt:
    name: qemu-guest-agent
    state: present
    update_cache: yes
  notify: Reiniciando qemu-guest-agent.service

- name: Instalando qemu-guest-agent via pacman
  when: ansible_distribution == 'Archlinux'
  pacman:
    name: qemu-guest-agent
    state: present
    update_cache: yes
  notify: Reiniciando qemu-ga.service

- name: Instalando open-vm-tools via apt
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt:
    name: open-vm-tools
    state: present
    update_cache: yes
  notify: Reiniciando open-vm-tools.service

- name: Instalando open-vm-tools via pacman
  when: ansible_distribution == 'Archlinux'
  pacman:
    name: open-vm-tools
    state: present
    update_cache: yes
  notify: Reiniciando vmtoolsd.service

...