---

- name: Instalando qemu-guest-agent via apt
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt:
    name: qemu-guest-agent
    state: present
    update_cache: yes

- name: Instalando qemu-guest-agent via pacman
  when: ansible_distribution == 'Archlinux'
  pacman:
    name: qemu-guest-agent
    state: present
    update_cache: yes

- name: Instalando open-vm-tools via apt
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt:
    name: open-vm-tools
    state: present
    update_cache: yes

- name: Instalando open-vm-tools via pacman
  when: ansible_distribution == 'Archlinux'
  pacman:
    name: open-vm-tools
    state: present
    update_cache: yes

- name: Iniciando qemu-guest-agent.service
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  systemd:
    name: qemu-guest-agent
    state: started
    enabled: yes

- name: Iniciando qemu-ga.service
  when: ansible_distribution == 'Archlinux'
  systemd:
    name: qemu-ga
    state: started
    enabled: yes

- name: Iniciando open-vm-tools.service
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  systemd:
    name: open-vm-tools
    state: started
    enabled: yes

- name: Iniciando vmtoolsd.service
  when: ansible_distribution == 'Archlinux'
  systemd:
    name: vmtoolsd
    state: started
    enabled: yes

...