---

- name: Copiando ~/.ssh/authorized_keys
  copy:
    src: authorized_keys
    dest: "/home/{{ ansible_distribution | lower }}/.ssh/authorized_keys"
    owner: "{{ ansible_distribution | lower }}"
    group: "{{ ansible_distribution | lower }}"
    force: yes

- name: Copiando /root/.ssh/authorized_keys
  copy:
    src: authorized_keys-root
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    force: yes

...